language: node_js

node_js:
    - "stable"
    - "<%= nodeVersion %>"

notifications:
    email: false

branches:
  only:
    - master
    - /^v[0-9].*$/
<% if (tests !== 'none') { %>
after_success:
  - npm run report-coverage -- -e TRAVIS_NODE_VERSION<% } %>
