language: node_js

node_js:
  - "stable"
  - "<%= nodeVersion %>"

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^v[0-9].*$/
<% if (tests !== 'none') { %>

after_success:
  - npm run report-coverage -- -e TRAVIS_NODE_VERSION<% } %>
